FROM node:20.17.0

# Set working directory
WORKDIR /app

# Install dependencies only when package files change
COPY package*.json ./
RUN npm install

# Expose port
EXPOSE 3000

# Run in development mode
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"] 