"use client"

import type React from "react"
import { createContext, useContext, useState, type ReactNode } from "react"

export type LanguageCode = "en" | "it" | "es"

interface Translations {
  [key: string]: string
}

interface LanguageContextType {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
  t: (key: string, params?: Record<string, string | number>) => string
}


const defaultTranslations: Record<LanguageCode, Translations> = {
  en: {
    "nav.courses": "Courses",
    "nav.createCourse": "Create Course",
    "nav.aboutUs": "About Us",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "app.title": "Course Generator",
    "footer.rights": "All rights reserved.",
    "courseList.title": "Course Generator",
    "courseList.subtitle": "Create and manage your educational courses",
    "courseList.createButton": "Create New Course",
    "courseList.noCourses": "No courses yet",
    "courseList.getStarted": "Get started by creating your first course",
    "courseList.lessons": "Lessons",
    "courseList.view": "View",
    "courseList.configure": "Configure",
    "courseList.deleteTitle": "Delete Course",
    "courseList.deleteDescription":
      "Are you sure you want to delete this course? This action cannot be undone and will permanently delete all associated lessons and content.",
    "courseList.cancel": "Cancel",
    "courseList.delete": "Delete Course",
    "courseList.error": "Failed to load courses. Please try again.",
    "courseConfig.title": "Course Configuration",
    "courseConfig.description": "Set up your course parameters and manage documents",
    "courseConfig.language": "Language",
    "courseConfig.selectLanguage": "Select Language",
    "courseConfig.spanish": "Spanish",
    "courseConfig.english": "English",
    "courseConfig.italian": "Italian",
    "courseConfig.duration": "Duration (minutes)",
    "courseConfig.coursePrompt": "Course Prompt",
    "courseConfig.coursePromptPlaceholder": "Write here the prompt for the course ...",
    "courseConfig.coursePromptTip":
      "Tip: Be specific about the course content, target audience, and desired learning outcomes.",
    "courseConfig.enhancePrompt": "Enhance Prompt",
    "courseConfig.yes": "Yes",
    "courseConfig.no": "No",
    "courseConfig.documents": "Documents",
    "courseConfig.uploadDocument": "Upload Document",
    "courseConfig.uploading": "Uploading...",
    "courseConfig.noDocuments": "No documents uploaded for this course.",
    "courseConfig.generateCoursePlan": "Generate Course Plan",
    "courseConfig.generating": "Generating...",
    "courseConfig.viewLessons": "View Lessons",
    "courseConfig.documentUploadSuccess": "Document uploaded successfully",
    "courseConfig.documentUploadError": "Error uploading document",
    "courseConfig.documentDeleteSuccess": "Document deleted successfully",
    "courseConfig.documentDeleteError": "Error deleting document",
    "courseConfig.coursePlanGenerateSuccess": "Course plan generated successfully",
    "courseConfig.coursePlanGenerateError": "Error generating course plan",
    "courseConfig.fillAllFields": "Please complete all required fields",
    "courseConfig.generatePlan": "Generate Plan",
    "courseConfig.generatingPlan": "Generating Plan",
    "courseConfig.fastForward": "Fast Forward",
    "courseConfig.generatingFullCourse": "Generating Full Course",
    "courseConfig.fullCourseGenerationStarted": "Full course generation started",
    "courseConfig.fullCourseGenerateError": "Error generating full course",
    "lessonList.viewCompleteCourse": "View Complete Course",
    "lessonList.generateAllPlans": "Generate All Plans",
    "lessonList.generatingAllPlans": "Generating All Plans...",
    "lessonList.writeAllContents": "Write All Contents",
    "lessonList.writingAllContents": "Writing All Contents...",
    "lessonList.generateAllSlides": "Generate All Slides",
    "lessonList.generatingAllSlides": "Generating All Slides...",
    "lessonList.downloadAllSlides": "Download All Slides as PPTX",
    "lessonList.retry": "Retry",
    "lessonList.backToCourses": "Back to Courses",
    "lessonList.lessonTitle": "Lesson Title",
    "lessonList.duration": "Duration",
    "lessonList.lessonPrompt": "Lesson Prompt",
    "lessonList.lessonPromptPlaceholder": "Write the lesson prompt here...",
    "lessonList.generatePlan": "Generate Plan",
    "lessonList.regeneratePlan": "Regenerate Plan",
    "lessonList.generatingPlan": "Generating Plan...",
    "lessonList.writeContent": "Write Content",
    "lessonList.rewriteContent": "Rewrite Content",
    "lessonList.writingContent": "Writing Content...",
    "lessonList.generateSlides": "Generate Slides",
    "lessonList.regenerateSlides": "Regenerate Slides",
    "lessonList.generatingSlides": "Generating Slides...",
    "lessonList.downloadSlides": "Download Slides",
    "lessonList.sections": "Sections",
    "lessonList.untitledSection": "Untitled Section",
    "lessonList.editSection": "Edit Section",
    "lessonList.allSlidesDownloaded": "All slides downloaded successfully",
    "lessonList.failedToDownloadAllSlides": "Failed to download all slides. Please try again.",
    "sectionList.invalidLessonId": "Invalid lesson ID",
    "sectionList.invalidResponseFormat": "Invalid response format",
    "sectionList.fetchError": "Failed to fetch lesson data: {{error}}",
    "sectionList.fetchErrorGeneric": "Failed to fetch lesson data. Please try again.",
    "sectionList.retry": "Retry",
    "sectionList.backToLessons": "Back to Lessons",
    "sectionList.lessonTitle": "Lesson {{order}}",
    "sectionList.noSections": "No sections found for this lesson.",
    "sectionList.enterSectionTitle": "Enter section title",
    "sectionList.content": "Content",
    "sectionList.enterSectionContent": "Enter section content",
    "sectionList.description": "Description",
    "sectionList.shortDescription": "Short description",
    "sectionList.duration": "Duration (minutes)",
    "sectionList.durationPlaceholder": "e.g., 15",
    "sectionList.style": "Style",
    "sectionList.stylePlaceholder":
      "Writing style (e.g., formal and didactic, using accessible but technical language...)",
    "sectionList.styleDescription":
      "Describe the writing style, tone, and approach for this section. Be as specific as possible.",
    "sectionList.instructions": "Instructions",
    "sectionList.specialInstructions": "Special instructions",
    "sectionList.saveChanges": "Save Changes",
    "sectionList.editSlide": "Edit Slide",
    "sectionList.downloadSlide": "Download Slide",
    "sectionList.createSlide": "Create Slide",
    "slideEditor.title": "Edit Slide",
    "slideEditor.noData": "No slide data available",
    "slideEditor.slideTitle": "Title",
    "slideEditor.slideTitlePlaceholder": "Enter slide title",
    "slideEditor.bulletPoints": "Bullet Points",
    "slideEditor.bulletPointPlaceholder": "Bullet point {{number}}",
    "slideEditor.addBulletPoint": "Add Bullet Point",
    "slideEditor.additionalText": "Additional Text",
    "slideEditor.additionalTextPlaceholder": "Enter additional text for the slide",
    "slideEditor.background": "Background",
    "slideEditor.selectBackground": "Select background",
    "slideEditor.light": "Light",
    "slideEditor.dark": "Dark",
    "slideEditor.designPreset": "Design Preset",
    "slideEditor.selectPreset": "Select preset",
    "slideEditor.cancel": "Cancel",
    "slideEditor.saving": "Saving...",
    "slideEditor.saveChanges": "Save changes",
    "slideEditor.fetchError": "Failed to fetch slide data",
    "slideEditor.updateSuccess": "Slide updated successfully",
    "slideEditor.updateError": "Failed to update slide: {{error}}",
    "slideEditor.unknownError": "Unknown error",
    "slideEditor.preset.professional": "Professional",
    "slideEditor.preset.creative": "Creative",
    "slideEditor.preset.minimalist": "Minimalist",
    "slideEditor.preset.earthy": "Earthy",
    "slideEditor.preset.tech": "Tech",
    "slideEditor.preset.vibrant": "Vibrant",
    "slideEditor.preset.serene": "Serene",
    "slideEditor.preset.futuristic": "Futuristic",
    "slideEditor.preset.organic": "Organic",
    "slideEditor.preset.luxury": "Luxury",
    "footer.aboutTitle": "About Course Generator",
    "footer.aboutDescription":
      "Course Generator is a platform dedicated to creating and managing educational courses, empowering educators and learners worldwide.",
    "footer.quickLinks": "Quick Links",
    "footer.aboutUs": "About Us",
    "footer.courses": "Courses",
    "footer.blog": "Blog",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.termsOfService": "Terms of Service",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.cookiePolicy": "Cookie Policy",
    "footer.stayUpdated": "Stay Updated",
    "footer.subscribeText": "Subscribe to our newsletter for the latest updates.",
    "footer.emailPlaceholder": "Enter your email",
    "footer.subscribe": "Subscribe",
    "footer.copyright": "Course Generator. All rights reserved.",
    "footer.website": "Website",
    "footer.email": "Email",
    "footer.chat": "Chat",
    "footer.phone": "Phone",
    "footer.location": "Location",
    "createCourse.title": "Create New Course",
    "createCourse.subtitle": "Fill in the details below to create a new educational course",
    "createCourse.courseDetails": "Course Details",
    "createCourse.provideInfo": "Provide the basic information for your new course",
    "createCourse.courseName": "Course Name",
    "createCourse.courseNamePlaceholder": "e.g., Introduction to Machine Learning",
    "createCourse.courseDescription": "Course Description",
    "createCourse.courseDescriptionPlaceholder": "Provide a brief overview of the course content and objectives...",
    "createCourse.createCourse": "Create Course",
    "createCourse.creatingCourse": "Creating Course...",
    "createCourse.enterCourseName": "Please enter a course name",
    "createCourse.failedToCreate": "Failed to create course",
    "createCourse.courseCreated": "Course created successfully",
    "createCourse.errorCreating": "Failed to create course. Please try again.",
    "completeCourse.fetchError": "Failed to fetch course data: {{status}} {{statusText}}",
    "completeCourse.loadError": "Failed to load course data. Please try again later.",
    "completeCourse.retry": "Retry",
    "completeCourse.noCourseData": "No course data available",
    "completeCourse.duration": "Duration: {{hours}}h {{minutes}}m",
    "completeCourse.backToLessons": "Back to Lessons",
    "completeCourse.lessonDuration": "{{hours}}h {{minutes}}m",
    "completeCourse.section": "Section {{number}}",
    "completeCourse.sectionDuration": "{{hours}}h {{minutes}}m",
    "completeCourse.noSectionContent": "No content available for this section",
    "completeCourse.noSections": "This lesson has no sections yet",
    "completeCourse.noLessons": "This course has no lessons yet. Start by adding some lessons to your course.",
    "completeCourse.downloadAsPdf": "Download as PDF",
    "completeCourse.downloadingPdf": "Downloading PDF...",
    "completeCourse.pdfGenerationError": "Error generating PDF",
    "completeCourse.downloadError": "Download Error",
    "completeCourse.downloadSuccess": "PDF Downloaded successfully",
    "completeCourse.noContentAvaiable": "No content available for this course",
    "contact.title": "Contact Us",
    "contact.getInTouch": "Get in Touch",
    "contact.formDescription": "Fill out the form below and we will get back to you as soon as possible.",
    "contact.name": "Name",
    "contact.emailField": "Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.sending": "Sending...",
    "contact.sendMessage": "Send Message",
    "contact.contactInfo": "Contact Information",
    "contact.contactInfoDescription": "You can also reach us using the following information.",
    "contact.address": "123 Education Street, Learning City, 12345",
    "contact.phone": "+1 (555) 123-4567",
    "contact.contactEmail": "support@eduapp.com",
    "contact.messageSent": "Message sent successfully!",
    "lessonManagement.title": "Lesson Management",
    "sectionManagement.title": "Section Management",
    "courseConfig.uploadDocuments": "Upload Documents",
    "courseConfig.documentsUploadSuccess": "Documents uploaded successfully",
    "taskProgress.taskFailed": "Task Failed",
    "taskProgress.taskCompleted": "Task Completed",
    "taskProgress.processingTask": "Processing Task",
    "taskProgress.processing": "Processing...",
    "taskProgress.completed": "Completed",
    "taskProgress.taskCompletedSuccessfully": "Task completed successfully",
    "taskProgress.retry": "Retry",
    "taskProgress.close": "Close",
    "taskProgress.cancel": "Cancel",
    "taskProgress.generatingCoursePlan": "Generating Course Plan",
    "taskProgress.generatingLessonPlans": "Generating Lesson Plans",
    "taskProgress.generatingLessonPlan": "Generating Lesson Plan",
    "taskProgress.writingLessons": "Writing Lessons",
    "taskProgress.writingLesson": "Writing Lesson",
    "taskProgress.generatingSlides": "Generating Slides",
    "taskProgress.generatingLessonSlides": "Generating Lesson Slides",
    "taskProgress.generatingDetailedPlansParallel": "Generating Detailed Plans in Parallel",
    "taskProgress.removingPreviousSections": "Removing previous sections of lesson {{lessonNum}}/{{totalLessons}}",
    "taskProgress.generatingAndImprovingParallel": "Generating and Improving in Parallel",
    // Nuevas traducciones para CourseSlideSettings
    "courseSlideSettings.title": "Slide Settings",
    "courseSlideSettings.description":
      "Customize the appearance of all slides in this course. Changes will apply to all sections.",
    "courseSlideSettings.updating": "Updating...",
    "courseSlideSettings.applyToAll": "Apply Settings to All Slides",
    "courseSlideSettings.loadingLessons": "Loading lessons...",
    "courseSlideSettings.noLessons": "No lessons found for this course",
    "courseSlideSettings.foundLessons": "Found {{lessonCount}} lessons with a total of {{sectionCount}} sections",
    "courseSlideSettings.updatingProgress": "Updating {{current}} of {{total}} sections ({{percentage}}%)",
    "courseSlideSettings.slidesUpdated": "Updated {{count}} slides so far",
    "courseSlideSettings.fetchError": "Failed to fetch course data",
    "courseSlideSettings.updateError": "Failed to update slide settings",
    "courseSlideSettings.partialSuccess": "Updated {{updated}} slides successfully ({{failed}} failed)",
    "courseSlideSettings.allSuccess": "All slides updated successfully",
    "completeCourse.downloadSlides": "Download Slides",
    "completeCourse.back": "Back",
    "completeCourse.slidesNotFound": "Slides not found. Please generate them first.",
    "completeCourse.courseNotFound": "Course not found",
    "courseSlideSettings.preview": "Preview",
    "courseSlideSettings.sampleTitle": "Sample Slide Title",
    "courseSlideSettings.samplePoint1": "First key point of the presentation",
    "courseSlideSettings.samplePoint2": "Second important concept to highlight",
    "courseSlideSettings.resetToDefaults": "Reset to Defaults",
    "courseSlideSettings.confirmUpdate": "Are you sure you want to apply the '{{background}}' background and '{{preset}}' preset to all slides? This will update all slides in the course.",
    "courseSlideSettings.confirmTitle": "Confirm Settings Change",
    "courseSlideSettings.confirmDescription": "You are about to apply these settings to all slides in the course. This will update the appearance of all presentations.",
    "courseSlideSettings.previewTitle": "Preview of new style",
    "courseSlideSettings.confirm": "Apply Changes",
    "courseSlideSettings.updatingToast": "Updating slide settings",
    "courseSlideSettings.updatingDescription": "Applying {{background}} background and {{preset}} design to all slides",
    "courseSlideSettings.successDescription": "All slides have been updated with the new appearance settings",
    "courseSlideSettings.viewChanges": "View Changes",
    "courseSlideSettings.resetDescription": "Settings have been reset to default values",
    "common.cancel": "Cancel",
  },
  it: {
    "nav.courses": "Corsi",
    "nav.createCourse": "Crea Corso",
    "nav.aboutUs": "Chi Siamo",
    "nav.profile": "Profilo",
    "nav.settings": "Impostazioni",
    "app.title": "Generatore di Corsi",
    "footer.rights": "Tutti i diritti riservati.",
    "courseList.title": "Generatore di Corsi",
    "courseList.subtitle": "Crea e gestisci i tuoi corsi educativi",
    "courseList.createButton": "Crea Nuovo Corso",
    "courseList.noCourses": "Nessun corso ancora",
    "courseList.getStarted": "Inizia creando il tuo primo corso",
    "courseList.lessons": "Lezioni",
    "courseList.view": "Visualizza",
    "courseList.configure": 'Config  "Lezioni',
    "courseList.deleteTitle": "Elimina Corso",
    "courseList.deleteDescription":
      "Sei sicuro di voler eliminare questo corso? Questa azione non può essere annullata e cancellerà permanentemente tutte le lezioni e i contenuti associati.",
    "courseList.cancel": "Annulla",
    "courseList.delete": "Elimina Corso",
    "courseList.error": "Impossibile caricare i corsi. Per favore riprova.",
    "courseConfig.title": "Configurazione del Corso",
    "courseConfig.description": "Imposta i parametri del corso e gestisci i documenti",
    "courseConfig.language": "Lingua",
    "courseConfig.selectLanguage": "Seleziona Lingua",
    "courseConfig.spanish": "Spagnolo",
    "courseConfig.english": "Inglese",
    "courseConfig.italian": "Italiano",
    "courseConfig.duration": "Durata (minuti)",
    "courseConfig.coursePrompt": "Prompt del Corso",
    "courseConfig.coursePromptPlaceholder": "Scrivi qui il prompt per il corso ...",
    "courseConfig.coursePromptTip":
      "Suggerimento: Sii specifico riguardo al contenuto del corso, al pubblico target e ai risultati di apprendimento desiderati.",
    "courseConfig.enhancePrompt": "Migliora Prompt",
    "courseConfig.yes": "Sì",
    "courseConfig.no": "No",
    "courseConfig.documents": "Documenti",
    "courseConfig.uploadDocument": "Carica Documento",
    "courseConfig.uploading": "Caricamento...",
    "courseConfig.noDocuments": "Nessun documento caricato per questo corso.",
    "courseConfig.generateCoursePlan": "Genera Piano del Corso",
    "courseConfig.generating": "Generazione...",
    "courseConfig.viewLessons": "Visualizza Lezioni",
    "courseConfig.documentUploadSuccess": "Documento caricato con successo",
    "courseConfig.documentUploadError": "Errore durante il caricamento del documento",
    "courseConfig.documentDeleteSuccess": "Documento eliminato con successo",
    "courseConfig.documentDeleteError": "Errore durante l'eliminazione del documento",
    "courseConfig.coursePlanGenerateSuccess": "Piano del corso generato con successo",
    "courseConfig.coursePlanGenerateError": "Errore durante la generazione del piano del corso",
    "courseConfig.fillAllFields": "Si prega di completare tutti i campi obbligatori",
    "courseConfig.generatePlan": "Genera Piano",
    "courseConfig.generatingPlan": "Generazione Piano",
    "courseConfig.fastForward": "Avanzamento Rapido",
    "courseConfig.generatingFullCourse": "Generazione Corso Completo",
    "courseConfig.fullCourseGenerationStarted": "Generazione del corso completo avviata",
    "courseConfig.fullCourseGenerateError": "Errore durante la generazione del corso completo",
    "lessonList.viewCompleteCourse": "Visualizza Corso Completo",
    "lessonList.generateAllPlans": "Genera Tutti i Piani",
    "lessonList.generatingAllPlans": "Generazione di Tutti i Piani...",
    "lessonList.writeAllContents": "Scrivi Tutti i Contenuti",
    "lessonList.writingAllContents": "Scrittura di Tutti i Contenuti...",
    "lessonList.generateAllSlides": "Genera Tutte le Slide",
    "lessonList.generatingAllSlides": "Generazione di Tutte le Slide...",
    "lessonList.downloadAllSlides": "Scarica Tutte le Slide come PPTX",
    "lessonList.retry": "Riprova",
    "lessonList.backToCourses": "Torna ai Corsi",
    "lessonList.lessonTitle": "Titolo della Lezione",
    "lessonList.duration": "Durata",
    "lessonList.lessonPrompt": "Prompt della Lezione",
    "lessonList.lessonPromptPlaceholder": "Scrivi qui il prompt della lezione...",
    "lessonList.generatePlan": "Genera Piano",
    "lessonList.regeneratePlan": "Rigenera Piano",
    "lessonList.generatingPlan": "Generazione del Piano...",
    "lessonList.writeContent": "Scrivi Contenuto",
    "lessonList.rewriteContent": "Riscrivi Contenuto",
    "lessonList.writingContent": "Scrittura del Contenuto...",
    "lessonList.generateSlides": "Genera Slide",
    "lessonList.regenerateSlides": "Rigenera Slide",
    "lessonList.generatingSlides": "Generazione delle Slide...",
    "lessonList.downloadSlides": "Scarica Slide",
    "lessonList.sections": "Sezioni",
    "lessonList.untitledSection": "Sezione Senza Titolo",
    "lessonList.editSection": "Modifica Sezione",
    "lessonList.allSlidesDownloaded": "Tutte le slide scaricate con successo",
    "lessonList.failedToDownloadAllSlides": "Impossibile scaricare tutte le slide. Per favore riprova.",
    "sectionList.invalidLessonId": "ID lezione non valido",
    "sectionList.invalidResponseFormat": "Formato di risposta non valido",
    "sectionList.fetchError": "Impossibile recuperare i dati della lezione: {{error}}",
    "sectionList.fetchErrorGeneric": "Impossibile recuperare i dati della lezione. Per favore riprova.",
    "sectionList.retry": "Riprova",
    "sectionList.backToLessons": "Torna alle Lezioni",
    "sectionList.lessonTitle": "Lezione {{order}}",
    "sectionList.noSections": "Nessuna sezione trovata per questa lezione.",
    "sectionList.enterSectionTitle": "Inserisci il titolo della sezione",
    "sectionList.content": "Contenuto",
    "sectionList.enterSectionContent": "Inserisci il contenuto della sezione",
    "sectionList.description": "Descrizione",
    "sectionList.shortDescription": "Breve descrizione",
    "sectionList.duration": "Durata (minuti)",
    "sectionList.durationPlaceholder": "es., 15",
    "sectionList.style": "Stile",
    "sectionList.stylePlaceholder":
      "Stile di scrittura (es., formale e didattico, usando un linguaggio accessibile ma tecnico...)",
    "sectionList.styleDescription":
      "Descrivi lo stile di scrittura, il tono e l'approccio per questa sezione. Sii il più specifico possibile.",
    "sectionList.instructions": "Istruzioni",
    "sectionList.specialInstructions": "Istruzioni speciali",
    "sectionList.saveChanges": "Salva Modifiche",
    "sectionList.editSlide": "Modifica Slide",
    "sectionList.downloadSlide": "Scarica Slide",
    "sectionList.createSlide": "Crea Slide",
    "slideEditor.title": "Modifica Slide",
    "slideEditor.noData": "Nessun dato disponibile per la slide",
    "slideEditor.slideTitle": "Titolo",
    "slideEditor.slideTitlePlaceholder": "Inserisci il titolo della slide",
    "slideEditor.bulletPoints": "Punti Elenco",
    "slideEditor.bulletPointPlaceholder": "Punto elenco {{number}}",
    "slideEditor.addBulletPoint": "Aggiungi Punto Elenco",
    "slideEditor.additionalText": "Testo Aggiuntivo",
    "slideEditor.additionalTextPlaceholder": "Inserisci testo aggiuntivo per la slide",
    "slideEditor.background": "Sfondo",
    "slideEditor.selectBackground": "Seleziona sfondo",
    "slideEditor.light": "Chiaro",
    "slideEditor.dark": "Scuro",
    "slideEditor.designPreset": "Preset di Design",
    "slideEditor.selectPreset": "Seleziona preset",
    "slideEditor.cancel": "Annulla",
    "slideEditor.saving": "Salvataggio in corso...",
    "slideEditor.saveChanges": "Salva modifiche",
    "slideEditor.fetchError": "Impossibile recuperare i dati della slide",
    "slideEditor.updateSuccess": "Slide aggiornata con successo",
    "slideEditor.updateError": "Impossibile aggiornare la slide: {{error}}",
    "slideEditor.unknownError": "Errore sconosciuto",
    "slideEditor.preset.professional": "Professionale",
    "slideEditor.preset.creative": "Creativo",
    "slideEditor.preset.minimalist": "Minimalista",
    "slideEditor.preset.earthy": "Naturale",
    "slideEditor.preset.tech": "Tecnologico",
    "slideEditor.preset.vibrant": "Vivace",
    "slideEditor.preset.serene": "Sereno",
    "slideEditor.preset.futuristic": "Futuristico",
    "slideEditor.preset.organic": "Organico",
    "slideEditor.preset.luxury": "Lussuoso",
    "footer.aboutTitle": "Informazioni su Course Generator",
    "footer.aboutDescription":
      "Course Generator è una piattaforma dedicata alla creazione e gestione di corsi educativi, che dà potere agli educatori e agli studenti in tutto il mondo.",
    "footer.quickLinks": "Link Rapidi",
    "footer.aboutUs": "Chi Siamo",
    "footer.courses": "Corsi",
    "footer.blog": "Blog",
    "footer.contact": "Contatti",
    "footer.legal": "Legale",
    "footer.termsOfService": "Termini di Servizio",
    "footer.privacyPolicy": "Politica sulla Privacy",
    "footer.cookiePolicy": "Politica sui Cookie",
    "footer.stayUpdated": "Rimani Aggiornato",
    "footer.subscribeText": "Iscriviti alla nostra newsletter per ricevere gli ultimi aggiornamenti.",
    "footer.emailPlaceholder": "Inserisci la tua email",
    "footer.subscribe": "Iscriviti",
    "footer.copyright": "Course Generator. Tutti i diritti riservati.",
    "footer.website": "Sito web",
    "footer.email": "Email",
    "footer.chat": "Chat",
    "footer.phone": "Telefono",
    "footer.location": "Posizione",
    "createCourse.title": "Crea Nuovo Corso",
    "createCourse.subtitle": "Compila i dettagli qui sotto per creare un nuovo corso educativo",
    "createCourse.courseDetails": "Dettagli del Corso",
    "createCourse.provideInfo": "Fornisci le informazioni di base per il tuo nuovo corso",
    "createCourse.courseName": "Nome del Corso",
    "createCourse.courseNamePlaceholder": "es., Introduzione al Machine Learning",
    "createCourse.courseDescription": "Descrizione del Corso",
    "createCourse.courseDescriptionPlaceholder":
      "Fornisci una breve panoramica del contenuto e degli obiettivi del corso...",
    "createCourse.createCourse": "Crea Corso",
    "createCourse.creatingCourse": "Creazione del Corso...",
    "createCourse.enterCourseName": "Per favore, inserisci un nome per il corso",
    "createCourse.failedToCreate": "Impossibile creare il corso",
    "createCourse.courseCreated": "Corso creato con successo",
    "createCourse.errorCreating": "Errore nella creazione del corso. Per favore, riprova.",
    "completeCourse.fetchError": "Impossibile recuperare i dati del corso: {{status}} {{statusText}}",
    "completeCourse.loadError": "Impossibile caricare i dati del corso. Per favore riprova più tardi.",
    "completeCourse.retry": "Riprova",
    "completeCourse.noCourseData": "Nessun dato del corso disponibile",
    "completeCourse.duration": "Durata: {{hours}}h {{minutes}}m",
    "completeCourse.backToLessons": "Torna alle Lezioni",
    "completeCourse.lessonDuration": "{{hours}}h {{minutes}}m",
    "completeCourse.section": "Sezione {{number}}",
    "completeCourse.sectionDuration": "{{hours}}h {{minutes}}m",
    "completeCourse.noSectionContent": "Nessun contenuto disponibile per questa sezione",
    "completeCourse.noSections": "Questa lezione non ha ancora sezioni",
    "completeCourse.noLessons": "Questo corso non ha ancora lezioni. Inizia aggiungendo alcune lezioni al tuo corso.",
    "completeCourse.downloadAsPdf": "Scarica come PDF",
    "completeCourse.downloadingPdf": "Download PDF in corso...",
    "completeCourse.pdfGenerationError": "Errore nella generazione del PDF",
    "completeCourse.downloadError": "Errore di Download",
    "completeCourse.downloadSuccess": "PDF scaricato con successo",
    "completeCourse.noContentAvaiable": "Nessun contenuto disponibile per questo corso",
    "contact.title": "Contattaci",
    "contact.getInTouch": "Mettiti in Contatto",
    "contact.formDescription": "Compila il modulo sottostante e ti risponderemo il prima possibile.",
    "contact.name": "Nome",
    "contact.emailField": "Email",
    "contact.subject": "Oggetto",
    "contact.message": "Messaggio",
    "contact.sending": "Invio in corso...",
    "contact.sendMessage": "Invia Messaggio",
    "contact.contactInfo": "Informazioni di Contatto",
    "contact.contactInfoDescription": "Puoi anche raggiungerci utilizzando le seguenti informazioni.",
    "contact.address": "Via dell'Educazione 123, Città dell'Apprendimento, 12345",
    "contact.phone": "+1 (555) 123-4567",
    "contact.contactEmail": "support@eduapp.com",
    "contact.messageSent": "Messaggio inviato con successo!",
    "lessonManagement.title": "Gestione delle Lezioni",
    "sectionManagement.title": "Gestione delle Sezioni",
    "courseConfig.uploadDocuments": "Carica Documenti",
    "courseConfig.documentsUploadSuccess": "Documenti caricati con successo",
    "taskProgress.taskFailed": "Operazione Fallita",
    "taskProgress.taskCompleted": "Operazione Completata",
    "taskProgress.processingTask": "Elaborazione in Corso",
    "taskProgress.processing": "Elaborazione...",
    "taskProgress.completed": "Completato",
    "taskProgress.taskCompletedSuccessfully": "Operazione completata con successo",
    "taskProgress.retry": "Riprova",
    "taskProgress.close": "Chiudi",
    "taskProgress.cancel": "Annulla",
    "taskProgress.generatingCoursePlan": "Generazione del Piano del Corso",
    "taskProgress.generatingLessonPlans": "Generazione dei Piani delle Lezioni",
    "taskProgress.generatingLessonPlan": "Generazione del Piano della Lezione",
    "taskProgress.writingLessons": "Scrittura delle Lezioni",
    "taskProgress.writingLesson": "Scrittura della Lezione",
    "taskProgress.generatingSlides": "Generazione delle Slide",
    "taskProgress.generatingLessonSlides": "Generazione delle Slide della Lezione",
    "taskProgress.generatingDetailedPlansParallel": "Generazione di Piani Dettagliati in Parallelo",
    "taskProgress.removingPreviousSections":
      "Rimozione delle sezioni precedenti della lezione {{lessonNum}}/{{totalLessons}}",
    "taskProgress.generatingAndImprovingParallel": "Generazione e Miglioramento in Parallelo",
    "courseSlideSettings.title": "Impostazioni Slide",
    "courseSlideSettings.description":
      "Personalizza l'aspetto di tutte le slide in questo corso. Le modifiche si applicheranno a tutte le sezioni.",
    "courseSlideSettings.updating": "Aggiornamento in corso...",
    "courseSlideSettings.applyToAll": "Applica Impostazioni a Tutte le Slide",
    "courseSlideSettings.loadingLessons": "Caricamento lezioni...",
    "courseSlideSettings.noLessons": "Nessuna lezione trovata per questo corso",
    "courseSlideSettings.foundLessons": "Trovate {{lessonCount}} lezioni con un totale di {{sectionCount}} sezioni",
    "courseSlideSettings.updatingProgress": "Aggiornamento {{current}} di {{total}} sezioni ({{percentage}}%)",
    "courseSlideSettings.slidesUpdated": "Aggiornate {{count}} slide finora",
    "courseSlideSettings.fetchError": "Impossibile recuperare i dati del corso",
    "courseSlideSettings.updateError": "Impossibile aggiornare le impostazioni delle slide",
    "courseSlideSettings.partialSuccess": "Aggiornate {{updated}} slide con successo ({{failed}} fallite)",
    "courseSlideSettings.allSuccess": "Tutte le {{count}} slide aggiornate con successo",
    "completeCourse.downloadSlides": "Scarica Diapositive",
    "completeCourse.back": "Indietro",
    "completeCourse.slidesNotFound": "Diapositive non trovate. Per favore, generarle prima.",
    "completeCourse.courseNotFound": "Corso non trovato",
    "courseSlideSettings.preview": "Anteprima",
    "courseSlideSettings.sampleTitle": "Titolo Slide di Esempio",
    "courseSlideSettings.samplePoint1": "Primo punto chiave della presentazione",
    "courseSlideSettings.samplePoint2": "Secondo concetto importante da evidenziare",
    "courseSlideSettings.resetToDefaults": "Ripristina Predefiniti",
    "courseSlideSettings.confirmUpdate": "Sei sicuro di voler applicare lo sfondo '{{background}}' e il preset '{{preset}}' a tutte le slide? Questo aggiornerà tutte le slide del corso.",
    "courseSlideSettings.confirmTitle": "Conferma Modifica Impostazioni",
    "courseSlideSettings.confirmDescription": "Stai per applicare queste impostazioni a tutte le slide del corso. Questo aggiornerà l'aspetto di tutte le presentazioni.",
    "courseSlideSettings.previewTitle": "Anteprima del nuovo stile",
    "courseSlideSettings.confirm": "Applica Modifiche",
    "courseSlideSettings.updatingToast": "Aggiornamento impostazioni slide",
    "courseSlideSettings.updatingDescription": "Applicazione sfondo {{background}} e design {{preset}} a tutte le slide",
    "courseSlideSettings.successDescription": "Tutte le slide sono state aggiornate con le nuove impostazioni di aspetto",
    "courseSlideSettings.viewChanges": "Visualizza Modifiche",
    "courseSlideSettings.resetDescription": "Le impostazioni sono state ripristinate ai valori predefiniti",
    "common.cancel": "Annulla",
  },
  es: {
    "nav.courses": "Cursos",
    "nav.createCourse": "Crear Curso",
    "nav.aboutUs": "Sobre Nosotros",
    "nav.profile": "Perfil",
    "nav.settings": "Configuración",
    "app.title": "Generador de Cursos",
    "footer.rights": "Todos los derechos reservados.",
    "courseList.title": "Generador de Cursos",
    "courseList.subtitle": "Crea y gestiona tus cursos educativos",
    "courseList.createButton": "Crear Nuevo Curso",
    "courseList.noCourses": "No hay cursos aún",
    "courseList.getStarted": "Comienza creando tu primer curso",
    "courseList.lessons": "Lecciones",
    "courseList.view": "Ver",
    "courseList.configure": "Configurar",
    "courseList.deleteTitle": "Eliminar Curso",
    "courseList.deleteDescription":
      "¿Estás seguro de que quieres eliminar este curso? Esta acción no se puede deshacer y eliminará permanentemente todas las lecciones y contenido asociado.",
    "courseList.cancel": "Cancelar",
    "courseList.delete": "Eliminar Curso",
    "courseList.error": "Error al cargar los cursos. Por favor, inténtalo de nuevo.",
    "courseConfig.title": "Configuración del Curso",
    "courseConfig.description": "Configura los parámetros del curso y gestiona los documentos",
    "courseConfig.language": "Idioma",
    "courseConfig.selectLanguage": "Seleccionar Idioma",
    "courseConfig.spanish": "Español",
    "courseConfig.english": "Inglés",
    "courseConfig.italian": "Italiano",
    "courseConfig.duration": "Duración (minutos)",
    "courseConfig.coursePrompt": "Prompt del Curso",
    "courseConfig.coursePromptPlaceholder": "Escribe aquí el prompt para el curso ...",
    "courseConfig.coursePromptTip":
      "Consejo: Sé específico sobre el contenido del curso, el público objetivo y los resultados de aprendizaje deseados.",
    "courseConfig.enhancePrompt": "Mejorar Prompt",
    "courseConfig.yes": "Sí",
    "courseConfig.no": "No",
    "courseConfig.documents": "Documentos",
    "courseConfig.uploadDocument": "Subir Documento",
    "courseConfig.uploading": "Subiendo...",
    "courseConfig.noDocuments": "No hay documentos subidos para este curso.",
    "courseConfig.generateCoursePlan": "Generar Plan del Curso",
    "courseConfig.generating": "Generando...",
    "courseConfig.viewLessons": "Ver Lecciones",
    "courseConfig.documentUploadSuccess": "Documento subido con éxito",
    "courseConfig.documentUploadError": "Error al subir el documento",
    "courseConfig.documentDeleteSuccess": "Documento eliminado con éxito",
    "courseConfig.documentDeleteError": "Error al eliminar el documento",
    "courseConfig.coursePlanGenerateSuccess": "Plan del curso generado con éxito",
    "courseConfig.coursePlanGenerateError": "Error al generar el plan del curso",
    "courseConfig.fillAllFields": "Por favor, complete todos los campos requeridos",
    "courseConfig.generatePlan": "Generar Plan",
    "courseConfig.generatingPlan": "Generando Plan",
    "courseConfig.fastForward": "Avance Rápido",
    "courseConfig.generatingFullCourse": "Generando Curso Completo",
    "courseConfig.fullCourseGenerationStarted": "Generación del curso completo iniciada",
    "courseConfig.fullCourseGenerateError": "Error al generar el curso completo",
    "lessonList.viewCompleteCourse": "Ver Curso Completo",
    "lessonList.generateAllPlans": "Generar Todos los Planes",
    "lessonList.generatingAllPlans": "Generando Todos los Planes...",
    "lessonList.writeAllContents": "Escribir Todos los Contenidos",
    "lessonList.writingAllContents": "Escribiendo Todos los Contenidos...",
    "lessonList.generateAllSlides": "Generar Todas las Diapositivas",
    "lessonList.generatingAllSlides": "Generando Todas las Diapositivas...",
    "lessonList.downloadAllSlides": "Descargar Todas las Diapositivas como PPTX",
    "lessonList.retry": "Reintentar",
    "lessonList.backToCourses": "Volver a los Cursos",
    "lessonList.lessonTitle": "Título de la Lección",
    "lessonList.duration": "Duración",
    "lessonList.lessonPrompt": "Prompt de la Lección",
    "lessonList.lessonPromptPlaceholder": "Escribe aquí el prompt de la lección...",
    "lessonList.generatePlan": "Generar Plan",
    "lessonList.regeneratePlan": "Regenerar Plan",
    "lessonList.generatingPlan": "Generando Plan...",
    "lessonList.writeContent": "Escribir Contenido",
    "lessonList.rewriteContent": "Reescribir Contenido",
    "lessonList.writingContent": "Escribiendo Contenido...",
    "lessonList.generateSlides": "Generar Diapositivas",
    "lessonList.regenerateSlides": "Regenerar Diapositivas",
    "lessonList.generatingSlides": "Generando Diapositivas...",
    "lessonList.downloadSlides": "Descargar Diapositivas",
    "lessonList.sections": "Secciones",
    "lessonList.untitledSection": "Sección Sin Título",
    "lessonList.editSection": "Editar Sección",
    "lessonList.allSlidesDownloaded": "Todas las diapositivas descargadas con éxito",
    "lessonList.failedToDownloadAllSlides": "Error al descargar todas las diapositivas. Por favor, inténtalo de nuevo.",
    "sectionList.invalidLessonId": "ID de lección inválido",
    "sectionList.invalidResponseFormat": "Formato de respuesta inválido",
    "sectionList.fetchError": "Error al obtener los datos de la lección: {{error}}",
    "sectionList.fetchErrorGeneric": "Error al obtener los datos de la lección. Por favor, inténtalo de nuevo.",
    "sectionList.retry": "Reintentar",
    "sectionList.backToLessons": "Volver a las Lecciones",
    "sectionList.lessonTitle": "Lección {{order}}",
    "sectionList.noSections": "No se encontraron secciones para esta lección.",
    "sectionList.enterSectionTitle": "Ingresa el título de la sección",
    "sectionList.content": "Contenido",
    "sectionList.enterSectionContent": "Ingresa el contenido de la sección",
    "sectionList.description": "Descripción",
    "sectionList.shortDescription": "Descripción breve",
    "sectionList.duration": "Duración (minutos)",
    "sectionList.durationPlaceholder": "ej., 15",
    "sectionList.style": "Estilo",
    "sectionList.stylePlaceholder":
      "Estilo de escritura (ej., formal y didáctico, usando lenguaje accesible pero técnico...)",
    "sectionList.styleDescription":
      "Describe el estilo de escritura, tono y enfoque para esta sección. Sé lo más específico posible.",
    "sectionList.instructions": "Instrucciones",
    "sectionList.specialInstructions": "Instrucciones especiales",
    "sectionList.saveChanges": "Guardar Cambios",
    "sectionList.editSlide": "Editar Diapositiva",
    "sectionList.downloadSlide": "Descargar Diapositiva",
    "sectionList.createSlide": "Crear Diapositiva",
    "slideEditor.title": "Editar Diapositiva",
    "slideEditor.noData": "No hay datos disponibles para la diapositiva",
    "slideEditor.slideTitle": "Título",
    "slideEditor.slideTitlePlaceholder": "Ingrese el título de la diapositiva",
    "slideEditor.bulletPoints": "Puntos de Viñeta",
    "slideEditor.bulletPointPlaceholder": "Punto de viñeta {{number}}",
    "slideEditor.addBulletPoint": "Agregar Punto de Viñeta",
    "slideEditor.additionalText": "Texto Adicional",
    "slideEditor.additionalTextPlaceholder": "Ingrese texto adicional para la diapositiva",
    "slideEditor.background": "Fondo",
    "slideEditor.selectBackground": "Seleccionar fondo",
    "slideEditor.light": "Claro",
    "slideEditor.dark": "Oscuro",
    "slideEditor.designPreset": "Preset de Diseño",
    "slideEditor.selectPreset": "Seleccionar preset",
    "slideEditor.cancel": "Cancelar",
    "slideEditor.saving": "Guardando...",
    "slideEditor.saveChanges": "Guardar cambios",
    "slideEditor.fetchError": "Error al obtener los datos de la diapositiva",
    "slideEditor.updateSuccess": "Diapositiva actualizada con éxito",
    "slideEditor.updateError": "Error al actualizar la diapositiva: {{error}}",
    "slideEditor.unknownError": "Error desconocido",
    "slideEditor.preset.professional": "Profesional",
    "slideEditor.preset.creative": "Creativo",
    "slideEditor.preset.minimalist": "Minimalista",
    "slideEditor.preset.earthy": "Natural",
    "slideEditor.preset.tech": "Tecnológico",
    "slideEditor.preset.vibrant": "Vibrante",
    "slideEditor.preset.serene": "Sereno",
    "slideEditor.preset.futuristic": "Futurista",
    "slideEditor.preset.organic": "Orgánico",
    "slideEditor.preset.luxury": "Lujo",
    "footer.aboutTitle": "Acerca de Course Generator",
    "footer.aboutDescription":
      "Course Generator es una plataforma dedicada a crear y gestionar cursos educativos, empoderando a educadores y estudiantes en todo el mundo.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.aboutUs": "Sobre Nosotros",
    "footer.courses": "Cursos",
    "footer.blog": "Blog",
    "footer.contact": "Contacto",
    "footer.legal": "Legal",
    "footer.termsOfService": "Términos de Servicio",
    "footer.privacyPolicy": "Política de Privacidad",
    "footer.cookiePolicy": "Política de Cookies",
    "footer.stayUpdated": "Mantente Actualizado",
    "footer.subscribeText": "Suscríbete a nuestro boletín para recibir las últimas actualizaciones.",
    "footer.emailPlaceholder": "Ingresa tu correo electrónico",
    "footer.subscribe": "Suscribirse",
    "footer.copyright": "Course Generator. Todos los derechos reservados.",
    "footer.website": "Sitio web",
    "footer.email": "Correo electrónico",
    "footer.chat": "Chat",
    "footer.phone": "Teléfono",
    "footer.location": "Ubicación",
    "createCourse.title": "Crear Nuevo Curso",
    "createCourse.subtitle": "Completa los detalles a continuación para crear un nuevo curso educativo",
    "createCourse.courseDetails": "Detalles del Curso",
    "createCourse.provideInfo": "Proporciona la información básica para tu nuevo curso",
    "createCourse.courseName": "Nombre del Curso",
    "createCourse.courseNamePlaceholder": "ej., Introducción al Aprendizaje Automático",
    "createCourse.courseDescription": "Descripción del Curso",
    "createCourse.courseDescriptionPlaceholder":
      "Proporciona una breve descripción del contenido y objetivos del curso...",
    "createCourse.createCourse": "Crear Curso",
    "createCourse.creatingCourse": "Creando Curso...",
    "createCourse.enterCourseName": "Por favor, ingresa un nombre para el curso",
    "createCourse.failedToCreate": "No se pudo crear el curso",
    "createCourse.courseCreated": "Curso creado exitosamente",
    "createCourse.errorCreating": "Error al crear el curso. Por favor, inténtalo de nuevo.",
    "completeCourse.fetchError": "Error al obtener los datos del curso: {{status}} {{statusText}}",
    "completeCourse.loadError": "Error al cargar los datos del curso. Por favor, inténtalo de nuevo más tarde.",
    "completeCourse.retry": "Reintentar",
    "completeCourse.noCourseData": "No hay datos del curso disponibles",
    "completeCourse.duration": "Duración: {{hours}}h {{minutes}}m",
    "completeCourse.backToLessons": "Volver a las Lecciones",
    "completeCourse.lessonDuration": "{{hours}}h {{minutes}}m",
    "completeCourse.section": "Sección {{number}}",
    "completeCourse.sectionDuration": "{{hours}}h {{minutes}}m",
    "completeCourse.noSectionContent": "No hay contenido disponible para esta sección",
    "completeCourse.noSections": "Esta lección aún no tiene secciones",
    "completeCourse.noLessons": "Este curso aún no tiene lecciones. Comienza añadiendo algunas lecciones a tu curso.",
    "completeCourse.downloadAsPdf": "Descargar como PDF",
    "completeCourse.downloadingPdf": "Descargando PDF...",
    "completeCourse.pdfGenerationError": "Error al generar el PDF",
    "completeCourse.downloadError": "Error de Descarga",
    "completeCourse.downloadSuccess": "PDF descargado con éxito",
    "completeCourse.noContentAvaiable": "No hay contenido disponible para este curso",
    "contact.title": "Contáctenos",
    "contact.getInTouch": "Póngase en Contacto",
    "contact.formDescription":
      "Complete el formulario a continuación y nos pondremos en contacto con usted lo antes posible.",
    "contact.name": "Nombre",
    "contact.emailField": "Correo electrónico",
    "contact.subject": "Asunto",
    "contact.message": "Mensaje",
    "contact.sending": "Enviando...",
    "contact.sendMessage": "Enviar Mensaje",
    "contact.contactInfo": "Información de Contacto",
    "contact.contactInfoDescription": "También puede comunicarse con nosotros utilizando la siguiente información.",
    "contact.address": "Calle Educación 123, Ciudad del Aprendizaje, 12345",
    "contact.phone": "+1 (555) 123-4567",
    "contact.contactEmail": "soporte@eduapp.com",
    "contact.messageSent": "¡Mensaje enviado con éxito!",
    "lessonManagement.title": "Gestión de Lecciones",
    "sectionManagement.title": "Gestión de Secciones",
    "courseConfig.uploadDocuments": "Subir Documentos",
    "courseConfig.documentsUploadSuccess": "Documentos subidos con éxito",
    "taskProgress.taskFailed": "Tarea Fallida",
    "taskProgress.taskCompleted": "Tarea Completada",
    "taskProgress.processingTask": "Procesando Tarea",
    "taskProgress.processing": "Procesando...",
    "taskProgress.completed": "Completado",
    "taskProgress.taskCompletedSuccessfully": "Tarea completada con éxito",
    "taskProgress.retry": "Reintentar",
    "taskProgress.close": "Cerrar",
    "taskProgress.cancel": "Cancelar",
    "taskProgress.generatingCoursePlan": "Generando Plan del Curso",
    "taskProgress.generatingLessonPlans": "Generando Planes de Lecciones",
    "taskProgress.generatingLessonPlan": "Generando Plan de Lección",
    "taskProgress.writingLessons": "Escribiendo Lecciones",
    "taskProgress.writingLesson": "Escribiendo Lección",
    "taskProgress.generatingSlides": "Generando Diapositivas",
    "taskProgress.generatingLessonSlides": "Generando Diapositivas de Lección",
    "taskProgress.generatingDetailedPlansParallel": "Generando Planes Detallados en Paralelo",
    "taskProgress.removingPreviousSections":
      "Eliminando secciones previas de la lección {{lessonNum}}/{{totalLessons}}",
    "taskProgress.generatingAndImprovingParallel": "Generando y Mejorando en Paralelo",
    // Nuevas traducciones para CourseSlideSettings
    "courseSlideSettings.title": "Configuración de Diapositivas",
    "courseSlideSettings.description":
      "Personaliza la apariencia de todas las diapositivas en este curso. Los cambios se aplicarán a todas las secciones.",
    "courseSlideSettings.updating": "Actualizando...",
    "courseSlideSettings.applyToAll": "Aplicar Configuración a Todas las Diapositivas",
    "courseSlideSettings.loadingLessons": "Cargando lecciones...",
    "courseSlideSettings.noLessons": "No se encontraron lecciones para este curso",
    "courseSlideSettings.foundLessons":
      "Se encontraron {{lessonCount}} lecciones con un total de {{sectionCount}} secciones",
    "courseSlideSettings.updatingProgress": "Actualizando {{current}} de {{total}} secciones ({{percentage}}%)",
    "courseSlideSettings.slidesUpdated": "Actualizadas {{count}} diapositivas hasta ahora",
    "courseSlideSettings.fetchError": "Error al obtener los datos del curso",
    "courseSlideSettings.updateError": "Error al actualizar la configuración de diapositivas",
    "courseSlideSettings.partialSuccess": "Actualizadas {{updated}} diapositivas con éxito ({{failed}} fallidas)",
    "courseSlideSettings.allSuccess": "Todas las {{count}} diapositivas actualizadas con éxito",
    "completeCourse.downloadSlides": "Descargar Diapositivas",
    "completeCourse.back": "Volver",
    "completeCourse.slidesNotFound": "Diapositivas no encontradas. Por favor, genéralas primero.",
    "completeCourse.courseNotFound": "Curso no encontrado",
    "courseSlideSettings.preview": "Anteprima",
    "courseSlideSettings.sampleTitle": "Titolo Slide di Esempio",
    "courseSlideSettings.samplePoint1": "Primo punto chiave della presentazione",
    "courseSlideSettings.samplePoint2": "Secondo concetto importante da evidenziare",
    "courseSlideSettings.resetToDefaults": "Ripristina Predefiniti",
    "courseSlideSettings.confirmUpdate": "Sei sicuro di voler applicare lo sfondo '{{background}}' e il preset '{{preset}}' a tutte le slide? Questo aggiornerà tutte le slide del corso.",
    "courseSlideSettings.confirmTitle": "Confirmar Cambio de Configuración",
    "courseSlideSettings.confirmDescription": "Estás a punto de aplicar esta configuración a todas las diapositivas del curso. Esto actualizará la apariencia de todas las presentaciones.",
    "courseSlideSettings.previewTitle": "Vista previa del nuevo estilo",
    "courseSlideSettings.confirm": "Aplicar Cambios",
    "courseSlideSettings.updatingToast": "Actualizando configuración de diapositivas",
    "courseSlideSettings.updatingDescription": "Aplicando fondo {{background}} y diseño {{preset}} a todas las diapositivas",
    "courseSlideSettings.successDescription": "Todas las diapositivas han sido actualizadas con la nueva configuración de apariencia",
    "courseSlideSettings.viewChanges": "Ver Cambios",
    "courseSlideSettings.resetDescription": "La configuración ha sido restablecida a los valores predeterminados",
    "common.cancel": "Cancelar",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>("en")

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = defaultTranslations[language][key] || key

    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{{${paramKey}}}`, String(paramValue))
      })
    }

    return translation
  }

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

